### ISSUE TITLE
Using environment or recipe variable just more than in lifecycle.

### ISSUE THREAD

**Issue by supavit28** [aws-greengrass/aws-greengrass-nucleus#1035]
**Feature Description**
Now AWS Greengrass's lifecycle can use both [environment variable](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-environment-variables.html) and [recipe variable](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-variables) but only in lifecycle.
I think it would be great if we can use those variables or even more from system environment variables (which may be complicated).

**Use Case**
For example in my use case, I store some component's artifacts on S3 bucket where its S3 url contain IoT Thing name.
This component recipe is widely use in multiple IoT Thing but just change only S3 url in Thing name. 
Instead of creating new component for every IoT Thing or IoT Group, I can use environment variable.

```
...
Manifests:
  Artifacts:
  - Uri: "s3://my-beautiful-bucket/{iot:thingName}/hello_world.py"
```

**Proposed Solution**
Add feature to using [environment variable](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-environment-variables.html) and [recipe variable](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-variables) not just only in recipe's lifecycle.

**Other**
Sorry if I opened issued in wrong place. I try to solve my problem and found maybe it is good to have this feature.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi @supavit28,
Thank you for your interest in Greengrass. Unfortunately the feature that you are requesting is not possible because Greengrass artifacts need to be fully known at the time that the component is created, not just when the component is deployed. 

If you want to download a file which is specific to your IoT Thing, then that is possible by using the AWS CLI or AWS SDK in your component. As part of the `run` lifecycle, you can use the TokenExchangeService to get AWS credentials and then use those credentials to download from S3.

**Comment by supavit-j** [comment]
@MikeDombo Thank for comment and suggestion.

**Comment by supavit28** [comment]
@MikeDombo Thank you for comment and suggestion.
