### ISSUE TITLE
GreenGrassV2 Core: Deviceless Provisioning

### ISSUE THREAD

**Issue by QuantumLove** [aws-greengrass/aws-greengrass-nucleus#840]
**Feature Description**

We should be able to provision a Greengrass core device without running the installer.

The output of this step is:
* A GreengrassV2 core device in AWS.
* Certificates+other artifacts to later on put on a device if we want.

**Use Case**

We distribute "vanilla" devices. These come with all the needed software but without any credentials.
When our clients activates our devices, they go through a setup wizard which results in downloading the certificates/credentials for their own AWS IoT thing, thus becoming an authenticated device.

With GreengrassV2, it seems that you can only provision a device when you install greengrass core??

*We don't want the devices to have the ability to provision devices*.

I see that there is a `config-init` flag in the installer, but it does not seem to be possible to provision the device outside of the installation workflow.

**Proposed Solution**
Please include prototype/workaround/sketch/reference implementation

The installer with `--provision false` seems to make sense.
New API methods should be added so we can provision the device.
The installer can then have additional input configurations where you can point it to the certificates/existing configuration.

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi,
This is already possible to do, we just don't have a full guide created at this time. If you manually create everything needed you can then create a config.yaml file and provide it to Greengrass when installing, using the `--init-config` option as you pointed out. In order to determine what ought to be in that file, I'd recommend simply using our automatic provisioning and then taking the `<root>/config/effectiveConfig.yaml` file as your example. The things which will need to be changed are the certificate paths, iot endpoints, thing name, and iot role alias.

We'll work on adding documentation with more detailed instructions for doing this.

**Comment by QuantumLove** [comment]
Hi @MikeDombo,

Thank you for the fast reply.

I am able indeed to get:
* thing-name
* certificate (attached to the iot thing)
* iot endpoints

What is confusing me is the iot role alias: It seems that I need an additional IAM role to give my thing the permissions it needs to be an IoT Core Device.

The problem I am facing is that it seems that I need to create a role for the iotRoleAlias. Does this mean that I need to create an IAM role for each device I have? Because of course, it is not an option to give all devices [this policy](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/main/src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java#L203-L210) for our prod environment.

Currently, we use thing groups and attach thing policies to those groups, and chose which groups a device should have. The union of all policies that apply to each device, results in its permissions.

It seems now that I need to give both thing policies and an IAM role.

Is it possible to not have this iot role alias and just rely on the iot group policies? I am not understanding the difference between the iot policies and this IAM role that is attached to the certificate.

If the certificate is attached to the thing, and the thing has the necessary permissions through thing policies, is that not enough?

Another thing that is absolutely not possible for us, is to have AWS credentials available for the installer.

I will give it another go, I want to make this work, 
I am also fine with taking my findings and producing documentation to save some work from you guys.


PS: We do use ABAC in our policies, so it would not be 1 role per device, but thing policies are more flexible for iot use cases than IAM roles.

**Comment by MikeDombo** [comment]
The role alias is a pointer to an existing IAM role so that the device can assume that role to give it permissions to access services such as S3. There is a limit of 100 aliases per account, so you do not create an alias per-device, you should be sharing them between all your devices. You must create an IoT Thing Policy which allows that thing to use the role alias, and the role alias must point to an IAM role which trusts credentials.iot.amazonaws.com. You can have a look at the [IoT Core documentation](https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html) for this feature.

The role alias is required for accessing AWS resources which need traditional AWS credentials (ie. non-IoT services, since IoT uses TLS mutual auth).

**Comment by QuantumLove** [comment]
Okay, I think I got it!

The IAM Role is so the device has permissions that "traditionally" things are not able to do, because AWS IoT does not have that power. Makes all the sense in the world now since AWS IAM is centrally managing access to those other services.

This also means that the policies don't overlap, they grant different permissions.

Thank you very much!

**Comment by MikeDombo** [comment]
Yes, you've got it, exactly right.

**Comment by MikeDombo** [comment]
The manual provisioning documentation is now live. 

https://docs.aws.amazon.com/greengrass/v2/developerguide/manual-installation.html
